# Generated by Django 5.1.4 on 2025-01-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_tcduser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcduser',
            name='two_factor_authorization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tcduser',
            name='two_factor_secret_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
