# Generated by Django 5.1.4 on 2025-02-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneOnOneMatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('point1', models.IntegerField(default=0)),
                ('point2', models.IntegerField(default=0)),
                ('match_day', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('round1_point1', models.IntegerField(default=0)),
                ('round1_point2', models.IntegerField(default=0)),
                ('round2_point1', models.IntegerField(default=0)),
                ('round2_point2', models.IntegerField(default=0)),
                ('round3_point1', models.IntegerField(default=0)),
                ('round3_point2', models.IntegerField(default=0)),
                ('round4_point1', models.IntegerField(default=0)),
                ('round4_point2', models.IntegerField(default=0)),
                ('match_day', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOneOnOneGameRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserTournamentGameRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
