# Generated by Django 5.1.4 on 2025-02-16 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oneononematch',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oneononematch',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='round1_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round1_player1_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='round1_player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round1_player2_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='round2_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round2_player1_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='round2_player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round2_player2_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='round3_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round3_player1_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='round3_player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round3_player2_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='round4_player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round4_player1_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='round4_player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round4_player2_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useroneononegamerecord',
            name='one_on_one_match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_records.oneononematch'),
        ),
        migrations.AddField(
            model_name='useroneononegamerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertournamentgamerecord',
            name='tournament_match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_records.tournamentmatch'),
        ),
        migrations.AddField(
            model_name='usertournamentgamerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
