# Generated by Django 5.1.4 on 2025-02-16 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactor',
            fields=[
                ('custom_user', models.OneToOneField(help_text='유저 외래키', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('two_factor_qr_code_image', models.FileField(help_text='2FA 등록 QR코드 이미지 경로', null=True, upload_to='two_factor_qr_code/')),
                ('two_factor_secret_code', models.CharField(help_text='2FA 고유 시크릿 키', max_length=100, null=True)),
            ],
        ),
    ]
